version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tencentcloud-sdk-python
    versions:
    - 3.0.375
